project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NYC Traffic Accident Density"
  author:
    - Shurui Li (sl5432)
    - Haonan Duan (hd2545)
  repo-url: https://github.com/ArixLi/NYCTrafficAccident
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: lux
    code-fold: true


