# Conclusion

After a thorough research into New York City's traffic accidents, we now have a better understanding of the traffic accidents across different boroughs in New York City, the factors contributing to the accidents, and we are able to answer the key questions of our interests.

The traffic accidents vary across different boroughs of NYC in which Queens has relatively higher counts of traffic accidents across 2016-2023. According to our interactive Choropleth map, the traffic accident density is densed in certain blocks which are the exit of George Washington Bridge, the right side of Alexander Hamilton Bridge, the left side of Queens-Midtown Tunnel, etc.

The primary contribution factors to traffic accidents are notably `Crossing`, `Traffic_Signal`, and `Junction`. According to our ridgeline plot, the extreme weathers also contribute to traffic accidents where traffic accidents are peaked in relatively cold or warm weathers.

The quantity of traffic accidents do vary with time where it varies with month of the year and with years, The number of traffic accidents tends to increase over 2016-2022 and is peaked at 2022. Since the data only included accidents until March 2023, we are expecting the number of accidents of 2023 ends up higher than 2022. Especially, in our interactive d3 graph, it's easy to see that the number of accidents caused by top three factors peaks at May and is relative high until October. Counter-intuitively, the number of accidents are lower when in winter where we expect road conditions to be bad. One of the reasons could be people tend to concentrate and be careful when they know that driving in winter is dangerous. The reasons behind this trend over month of the year is another interesting topic needing further analysis and research. However, the reasons causing traffic accidents do not vary with different boroughs of NYC.

The research has a few limitations such as the data collection where we have missing values of geological information, and for half of the accidents, we are missing the factors causing it. Thus, it is imperative to retreat those informations.

Further research could focus on the factors causing the traffic accidents in a way that we consider more specific factors instead of a few main factors in our dataset. Besides, the reason why traffic accidents are higher in summer than in winter is worth exploring, and this would be another aspect of future research,

In conclusion, when you drive in New York City, you should be extremely careful when in summer, when in Queens, when entering or exiting a bridge, when crossing, waiting for signal, and encountering a junction.



